---
title: "Staying in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
output: 
   html_document:
      number_sections: TRUE
      fig_caption: TRUE
      toc: TRUE
      toc_depth: 5
      toc_float: TRUE
      theme:
         bootswatch: minty
         # bootswatch: cosmo
      highlight: espresso
      # espresso, tango, zenburn
      code_folding: hide
      # code_download: TRUE
      fig_width: 10
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(plotly)
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(RColorBrewer)  # display.brewer.all()
library(extrafont)  # "Candara"

# Descriptive Statistics
library(naniar)
library(psych)
library(gtsummary)

# GeoSpatial Analysis
source("utility/geospatial.R")
library(rayshader)
```

## Environment
```{r Environment}
source("utility/helper_functions.R")
source("utility/environments.R")

col.rp <- col.r.p
col.cb <- col.c.b
col.bg <- "#262A33"
col.fg <- "#393F4D"
```

# Load DataSets {.tabset .tabset-fade .tabset-pills}

https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P09.html

```{r Load DataSets}
admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
) %>% 
    rmapshaper::ms_filter_islands(min_area = 1e8) %>% 
    st_transform(crs.base)
```

```{r}
admin.code <- readxl::read_excel(
  "input/AdminiBoundary_CD.xlsx", skip = 1
) %>% rename("District" = "行政区域コード")
```

```{r}
stay.sf <- sf::read_sf(
    "input/Accomodation_2010/P09-10_5339-jgd-g_AccommodationCapacityMesh.shp"
) %>% sf::st_set_crs(crs.base) %>% 
    rename(ROOMS = P09_014) %>% 
    mutate(ROOMS = as.numeric(ROOMS))
```


# Preprocessing {.tabset .tabset-fade .tabset-pills}
## Concat Polygons by District
```{r}
admin.sf <- admin.sf %>% 
    rename(District = N03_007) %>% 
    select(District) %>%
    group_by(District) %>%
    summarise(.groups = "drop") %>% 
    left_join(admin.code %>% select(District, City), by = "District")
```

## Remove polygons outside Tokyo districts
```{r}
admin.all.sf <- admin.sf %>% 
    select(City) %>% 
    summarise() %>% 
    sfheaders::sf_remove_holes()
```
```{r}
stay.sf <- stay.sf %>% 
    mutate(
        is.Tokyo = as.numeric(
            st_within(stay.sf$geometry, admin.all.sf$geometry)
        )
    ) %>% filter(!is.na(is.Tokyo)) %>% 
    select(-is.Tokyo)
```


# Choropleth Map: Tokyo
```{r, fig.height=15}
col.new <- colorRampPalette(
    c(col.fg, "#ECC5FB")
)
col.fill <- col.new(5)

p <- ggplot() + 
    geom_sf(mapping = aes(), data = admin.sf, 
            fill = col.fg, color = col.bg, alpha = 1, size = 0.1) + 
    geom_sf(mapping = aes(fill = ROOMS), 
            data = stay.sf %>% select(ROOMS), 
            color = NA, size = 0, alpha = 0.75) + 
    # rcartocolor::scale_fill_carto_c(name = "Rooms", palette = "Purp") + 
    scale_fill_gradientn(
        name = "Rooms",
        colours = col.fill,
        breaks = c(0, 100, 200, 400, 800),
        # labels = c(0, 100, 200, 400)
        # limits = c(0, 2000)
    ) +
    coord_sf(crs = crs.base) + 
    labs(x = NULL, y = NULL, 
         title = "Rooms to Stay in Tokyo", 
         caption = "#30DaysMapChallenge; @Maxwell_110") + 
    theme(
        title = element_text(size = 15, family = "Times New Roman", 
                             face = "bold", color = "#ECC5FB"), 
        plot.title = element_text(hjust = 0.1, vjust = 0.1), 
        plot.caption = element_text(color = "#ECC5FB", size = 10, 
                                    hjust = 0.9), 
        axis.text = element_blank(), 
        legend.position = c(0.1, 0.15), 
        legend.text = element_text(
            family = "Times New Roman", face = "bold", 
            size = 7, color = "#ECC5FB"
        ), 
        plot.margin = unit(c(0, 0, 30, 0), units = "pt"), 
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg)
        
    ) + 
    guides(fill = guide_legend(
        title.position = "top", 
        label.position = "right", 
        keyheight = unit(0.05, units = "npc"),
        keywidth = unit(0.06, units = "npc"), 
        byrow = T, 
        reverse = T
    ))

p
```

## 3D Map: Tokyo
```{r, fig.height=15}
rayshader::plot_gg(
    ggobj = p,
    # width = 7, height = 5,
    scale = 150,
    shadow_intensity = .75,
    sunangle = 360,
    offset_edges = T,
    windowsize = c(1400, 866),
    zoom = .4,
    phi = 30,
    theta = -30
)

rayshader::render_snapshot(
    filename = "Accomodation-3D_Tokyo.png", clear = T
)
```
