---
title: "Minimal in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(pals)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)

library(ggmap)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
source(file = "utility/geospatial.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()

# https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
crs.base <- "+proj=longlat +datum=WGS84"
register_google(key = readRDS(file = "api/google-api.RDS"))
loc.base <- c(lon = 139.709, lat = 35.697)
```


# Dataset

maptype:  
- "terrain", "terrain-background", "terrain-labels", "terrain-lines"  
- "satellite", "roadmap", "hybrid"  
- "toner", "toner-2010", "toner-2011", "toner-background", "toner-hybrid", "toner-labels", "toner-lines", "toner-lite"  
- "watercolor"

## ggmap
```{r}
tokyo.s <- get_map(
    location = loc.base, 
    zoom = 14,  # 3 (continent) to 21 (building)
    scale = 2, 
    maptype = "satellite", 
    source = "google",  # "google", "osm", "stamen", "cloudmademap"
    # source = "stamen",  # "google", "osm", "stamen", "cloudmademap"
    color = "color", 
    crop = TRUE
)
ggmap(tokyo.s)
```

<!-- ## Central Tokyo -->
<!-- ```{r} -->
<!-- admin.sf <- sf::read_sf( -->
<!--     "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp" -->
<!-- ) %>% rmapshaper::ms_filter_islands(min_area = 1e8) %>%  -->
<!--     st_transform(crs = crs.base) -->


<!-- admin.code <- readxl::read_excel( -->
<!--     "input/AdminiBoundary_CD.xlsx", skip = 1 -->
<!-- ) %>% rename("District" = "行政区域コード") -->

<!-- admin.sf <- admin.sf %>%  -->
<!--     rename(District = N03_007) %>%  -->
<!--     select(District) %>% -->
<!--     group_by(District) %>% -->
<!--     summarise(.groups = "drop") %>% -->
<!--     left_join(admin.code %>% select(District, City), by = "District") %>%  -->
<!--     filter(District <= 13123) -->

<!-- admin.df <- fortify(admin.sf) -->
<!-- ``` -->

## Metro Plan
```{r}
shinjuku.sf <- sf::read_sf(
    "input/Tokyo_2022/N03-22_13_220101.shp"
) %>% filter(N03_004 == "新宿区")
```


# Viz {.tabset .tabset-fade .tabset-pills}
## Draw
```{r}
# col.bg <- "gray95"
# col.bg <- "#092532"
col.bg <- "#262A33"
col.fg <- "#393F4D"
# arrow.df <- arrow.df(xb = 139.69, yb = 35.675, len = 0.005)
# label.df <- data.frame(x = 139.69, y = 35.68, lab = "N")

p <- ggmap(tokyo.s) + 
    geom_sf(inherit.aes = FALSE,
            data = shinjuku.sf,
            color = col.pr.pale.blue,
            # linetype = "21",
            size = 0.5, fill = NA, alpha = 0.5) + 
    geom_point(x = 139.702, y = 35.696, color = col.el, size = 2) + 
    geom_text(x = 139.702, y = 35.694, 
              label = "Kabuki-cho",
              color = col.el, size = 4,
              family = "Times New Roman") + 
    geom_point(x = 139.692, y = 35.689, color = col.el, size = 2) + 
    geom_text(x = 139.692, y = 35.686, 
              label = "Tokyo \nMetropolitan \nGovernment",
              color = col.el, size = 3,
              family = "Times New Roman") + 
    geom_point(x = 139.715, y = 35.678, color = col.el, size = 2) + 
    geom_text(x = 139.718, y = 35.681, 
              label = "National \nStadium",
              color = col.el, size = 3,
              family = "Times New Roman") + 
    labs(
        title = "Shinjuku District, Tokyo, Japan", 
        subtitle = "Minimal Map", 
        x = NULL, y = NULL, 
        caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    theme(
        title = element_text(
            family = "Times New Roman", face = "bold", 
            color = col.c.b, size = 12
        ), 
        plot.title = element_text(
            margin = margin(t = 0, r = -00, b = 0, l = 00, unit = "pt")
        ), 
        plot.subtitle = element_text(
            family = "Times New Roman", face = "bold", 
            color = col.c.b, size = 10, 
            hjust = 0.025, 
            margin = margin(t = 0, r = -00, b = 0, l = 00, unit = "pt")
        ), 
        plot.caption = element_text(color = col.c.b, size = 6), 
        text = element_text(family = "Times New Roman", 
                            face = "bold", color = col.fg), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        # legend.title = element_blank(),
        # legend.text = element_text(
        #     family = "Times New Roman", face = "plain", 
        #     color = col.c.b, 
        #     size = 5
        # ), 
        legend.position = c(0.875, 0.175), 
        legend.key.size = unit(0.015, "npc")
    ) + 
    guides(fill = guide_colourbar(
        title = "Number of Hospitals", 
        title.theme = element_text(
            family = "Times New Roman", face = "plain", 
            color = col.c.b, size = 5
            # angle = 90
        ), 
        title.position = "bottom", title.hjust = 0, title.vjust = -1, 
        barwidth = 0.4, barheight = 4, 
        label.theme = element_text(
            family = "Times New Roman", face = "plain", 
            color = col.c.b, size = 4
        ), 
        label.position = "right", 
        ticks.linewidth = 3, ticks.colour = col.bg
    ))
p

ggsave("fig/Minimal-in-Tokyo.jpg", width = 5, height = 5)
```
