---
title: "Railways in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()
```


# Dataset {.tabset .tabset-fade .tabset-pills}

https://nlftp.mlit.go.jp/ksj/index.html  

Station Codes: https://nlftp.mlit.go.jp/ksj/gml/codelist/TokyoAreaStationCd.html

```{r Dataset}
crs.base <- "+proj=longlat +datum=WGS84"

admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
) %>% rmapshaper::ms_filter_islands(min_area = 1e8)

admin.code <- readxl::read_excel(
    "input/AdminiBoundary_CD.xlsx", skip = 1
) %>% rename("District" = "行政区域コード")

rail.way.sf <- sf::read_sf(
    "input/Railway_Japan_2021/N02-21_RailroadSection.shp"
) %>% st_transform(crs.base)

# rail.stat.sf <- sf::read_sf(
#     "input/Railway_Japan_2021/N02-21_Station.shp"
# ) %>% st_transform(crs.base)

stat.sf <- sf::read_sf(
    "input/Station_Kanto_2010/S05-c-10_SYUTO-g_CommutersPerStation_TokyoUrbanArea.shp"
) %>% st_set_crs(crs.base)

lp.sf <- sf::read_sf("input/Land-Price_Tokyo_2022/L01-22_13.shp")

admin.sf <- admin.sf %>% st_transform(crs.base)
lp.sf <- lp.sf %>% st_transform(crs.base)

# tokyo.sf <- readRDS(file = "input/Tokyo_2022/tokoy.sf.RDS")
```


# Preprocessing
```{r}
admin.sf <- admin.sf %>% 
    rename(District = N03_007) %>% 
    select(District) %>%
    group_by(District) %>%
    summarise(.groups = "drop") %>%
    left_join(admin.code %>% select(District, City), by = "District")
```

```{r}
# Select features of getting in and out of stations.
stat.sf <- stat.sf %>% select(S05c_027, S05c_042, S05c_057) %>% 
    mutate(
        IN = as.integer(S05c_042), 
        OUT = as.integer(S05c_057), 
        INOUT = IN + OUT, 
        INOUT_CAT = cut(INOUT, breaks = quantile(INOUT))
    ) %>% 
    filter(!is.na(INOUT_CAT)) %>% 
    mutate(
        INOUT_CAT = factor(INOUT_CAT, 
            levels = c(
                "(0,4.71e+03]",
                "(4.71e+03,1.68e+04]",
                "(1.68e+04,3.71e+04]",
                "(3.71e+04,9.4e+05]"
            ),
            labels = c(
                "Min - Q1", "Q1 - Q2", 
                "Q2 - Q3", "Q3 - Max"
            )
        ))
```



# Viz

```{r}
col.bg <- "#262A33"
col.fg <- "#393F4D"

p1 <- ggplot(data = stat.sf) + 
    geom_sf(data = admin.sf %>% filter(District <= 13123), 
            size = 0.05, fill = col.fg, color = "gray50") + 
    lims(x = c(139.55, 139.95), y = c(35.5, 35.85)) + 
    geom_sf(data = rail.way.sf %>% select(geometry), 
            color = col.bmc.pink, size = 0.2) + 
    geom_sf(color = col.mt, size = 3, alpha = 1.0) + 
    facet_wrap(vars(INOUT_CAT), nrow = 2) + 
    labs(title = "Railway Networks in Central Tokyo by Number of Users", 
         subtitle = "Quartiles were calculated based on the users of all stations in Japan.\nData Source: https://nlftp.mlit.go.jp/ksj/index.html", 
         caption = "#30DaysMapChallenge; @Maxwell_110", 
         x = NULL, y = NULL) + 
    theme(
        title = element_text(
            # family = "Times New Roman", 
            face = "bold.italic",
            color = col.bmc.pink, size = 15
        ), 
        # plot.title = element_text(
        #     margin = margin(t = 10, r = -00, b = -10, l = 00, unit = "pt")
        # ), 
        plot.subtitle = element_text(
            # family = "Times New Roman", face = "plain", 
            face = "bold.italic", 
            color = col.bmc.pink, size = 13, 
            # margin = margin(t = 35, r = -00, b = -35, l = 00, unit = "pt")
        ), 
        text = element_text(face = font.face), 
        axis.text = element_text(family = font.base, face = font.face, 
                                 color = "gray50", size = 4), 
        strip.text = element_text(
            face = "bold.italic", color = col.bmc.pink, size = 15
        ), 
        strip.switch.pad.wrap = unit(0.1, "npc"), 
        legend.position = c(0.7, 0.15), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.caption = element_text(
            # family = "Times New Roman", 
            color = col.bmc.pink, size = 8
        ), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid = element_line(colour = col.bg), 
    )

p1
ggsave("fig/Railways.jpg", width = 4.5 * 1.2 * 2, height = 4.5 * 1.4 * 2)
```
