---
title: "Russians in Japan"
subtitle: ""
author: ""
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
   html_document:
      number_sections: TRUE
      fig_caption: TRUE
      toc: TRUE
      toc_depth: 5
      toc_float: TRUE
      theme:
         bootswatch: minty
         # bootswatch: cosmo
      highlight: espresso
      # espresso, tango, zenburn
      code_folding: show
      # code_download: TRUE
      fig_width: 10
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

# Preparations {.tabset .tabset-fade .tabset-pills}

## R Packages
```{r, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"
library(RColorBrewer)

# Interactivity
library(plotly)
library(crosstalk)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)  # ne_states

# Parallel
library(purrr)
library(foreach)
library(doParallel)

# Descriptive Statistics
library(naniar)
library(psych)
library(gtsummary)

# Multi Level Model
library(lme4)
library(lmerTest)
library(coefplot)

# Stan
library(rstan)
library(bayesplot)
library(broom)
library(broom.mixed)
```

## Environment
```{r Environment}
# rgb(73, 81, 112, maxColorValue = 255): "#495170"
col.tw <- "#dbd7d2"  # Timberwolf
col.os <- "#414a4c"  # Outer Space
col.rp <- "#7851a9"  # Royal Purple
col.pb <- "#1ca9c9"  # Pacific Blue
col.cb <- "#b0b7c6"  # Cadet Blue
col.el <- "#ceff1d"  # Electric Lime
col.cg <- "#00cc99"  # Caribbean Green
col.mt <- "#ff8243"  # Mango Tango
col.rm <- "#e3256b"  # Razzmatazz
col.sl <- "#fc2847"  # Scarlet
col.plos.ye <- "#D6E13D"  # PLOS ONE Yellow
col.plos.pink <- "#CF00A3"  # PLOS ONE Pink

col.bg <- "#262A33"
col.fg <- "#393F4D"

# font.base <- "Candara"
font.base <- "Times New Roman"
theme_set(theme_minimal(base_family = font.base))
options(dplyr.summarise.inform = TRUE)
# Twitter Logo and Acc
t.img <- png::readPNG("fig/twitter.png")
t.grob <- grid::rasterGrob(t.img, 
                           width = unit(0.4, "cm"), 
                           height = unit(0.4, "cm"),
                           interpolate = FALSE)
```

# Load DataSets {.tabset .tabset-fade .tabset-pills}
```{r Load DataSets}
jp.pop <- read_csv("input/Japan_pop.csv", 
                   locale = locale(encoding = "cp932")) %>% 
    filter(PREF != "沖縄県") %>% 
    rename(TOTAL_POP = POP)  # unit 1,000
russians <- read_csv("input/Russian.csv")

ne.jpn.sf <- ne_states(country = "Japan", returnclass = "sf") %>% 
    rmapshaper::ms_filter_islands(min_area = 1e10)  # remove small islands
```

# Preprocessing
```{r}
ne.jpn.sf <- ne.jpn.sf %>% 
    select(iso_3166_2, name, region, latitude, longitude) %>% 
    tibble::new_tibble(nrow = nrow(.), class = "sf") %>% 
    left_join(russians %>% select(Prefecture_name, Pop), 
              by = c("name" = "Prefecture_name")) %>% 
    arrange(iso_3166_2) %>% 
    bind_cols(jp.pop %>% select(TOTAL_POP))
glimpse(ne.jpn.sf)
```

```{r}
pop.jpn.sf <- ne.jpn.sf %>% 
    mutate(
        longitude = ifelse(name == "Nagasaki", 129.8, longitude), 
        latitude = ifelse(name == "Nagasaki", 33.1, latitude), 
        longitude = ifelse(name == "Kagoshima", 130.5, longitude), 
        latitude = ifelse(name == "Kagoshima", 31.6, latitude), 
    ) %>% 
    tibble() %>% 
    select(longitude, latitude, Pop, TOTAL_POP) %>% 
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
    st_transform(crs = st_crs(ne.jpn.sf)) %>% 
    mutate(
        Pop.size = Pop / max(Pop) * 5, 
        Rus.ratio = Pop / (TOTAL_POP * 10000) * 100  # %
    )
```


# Draw map
```{r, fig.height=13}
p1 <- ggplot(data = ne.jpn.sf) + 
    geom_sf(mapping = aes(), size = 0.05, fill = col.fg, color = "gray50") + 
    geom_sf(mapping = aes(size = Pop.size), data = pop.jpn.sf, 
            color = col.sl, alpha = 0.5) + 
    lims(x = c(128, 145), y = c(31, 45)) + 
    geom_sf_text(mapping = aes(label = Pop), 
                 data = ne.jpn.sf %>% filter(Pop > 100), 
                 color = col.tw, cex = 2, family = font.base) + 
    geom_text(aes(x = 133, y = 42, 
                  label = "Figures are shown for 100 or more."), 
              family = font.base, color = col.sl, size = 3) + 
    labs(x = NULL, y = NULL, title = NULL) + 
    guides(size = guide_legend(title = "Rus Pop\n(Rerative Scale)", 
                               keyheight = 0.5)) + 
    theme(
        title = element_text(color = col.tw, size = 20), 
        legend.position = c(0.85, 0.15), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.title = element_text(
            margin = margin(t = 30, r = -00, b = -30, l = 00, unit = "pt")
        ), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid = element_line(colour = col.bg), 
    )

p2 <- ggplot(data = ne.jpn.sf) + 
    geom_sf(mapping = aes(), size = 0.05, fill = col.fg, color = "gray50") + 
    geom_sf(mapping = aes(size = Rus.ratio * 1000), data = pop.jpn.sf, 
            color = col.el, alpha = 0.5) + 
    lims(x = c(128, 145), y = c(31, 45)) + 
    geom_sf_text(mapping = aes(label = Rus.ratio), 
                 data = pop.jpn.sf %>% filter(Rus.ratio > 0.001) %>% 
                     mutate(Rus.ratio = round(Rus.ratio * 1000, 1)), 
                 color = col.bg, cex = 2, family = font.base) + 
    geom_text(aes(x = 133, y = 42, 
                  label = "Figures are shown for 0.001% or more."), 
              family = font.base, color = col.el, size = 3) + 
    labs(x = NULL, y = NULL, title = NULL) + 
    guides(size = guide_legend(title = "Rerative Pop Ratio\n (x 1000%)")) + 
    theme(
        title = element_text(color = col.tw, size = 20), 
        legend.position = c(0.85, 0.15), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.title = element_text(
            margin = margin(t = 30, r = -00, b = -30, l = 00, unit = "pt")
        ), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid = element_line(colour = col.bg), 
    )

p1 + p2 + plot_annotation(
    title = "Russian Population by Prefecture", 
    theme = theme(title = element_text(color = col.tw, size = 20))
)
ggsave("fig/russians.png", width = 9, height = 9 * 0.6, dpi = 200)
```

