---
title: "Scale"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggmap)
library(ggalt)  # geom_encircle
library(patchwork)
library(pals)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()

# https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
crs.base <- "+proj=longlat +datum=WGS84"
register_google(key = readRDS(file = "api/google-api.RDS"))
loc.base <- c(lon = 139.73, lat = 35.70)
```


# Dataset

maptyle:  
- "terrain", "terrain-background", "terrain-labels", "terrain-lines"  
- "satellite", "roadmap", "hybrid"  
- "toner", "toner-2010", "toner-2011", "toner-background", "toner-hybrid", "toner-labels", "toner-lines", "toner-lite"  
- "watercolor"

## ggmap
```{r}
tokyo.s1 <- get_map(
    location = loc.base, 
    zoom = 11,  # 3 (continent) to 21 (building)
    scale = 3, 
    maptype = "terrain", 
    # source = "google",  # "google", "osm", "stamen", "cloudmademap"
    source = "stamen",  # "google", "osm", "stamen", "cloudmademap"
    color = "color", 
    crop = TRUE
)
ggmap(tokyo.s1)
```

```{r}
tokyo.s2 <- get_map(
    location = loc.base, 
    zoom = 9,  # 3 (continent) to 21 (building)
    scale = 3, 
    maptype = "terrain", 
    # source = "google",  # "google", "osm", "stamen", "cloudmademap"
    source = "stamen",  # "google", "osm", "stamen", "cloudmademap"
    color = "color", 
    crop = TRUE
)
ggmap(tokyo.s2)
```

```{r}
tokyo.s3 <- get_map(
    location = loc.base, 
    zoom = 7,  # 3 (continent) to 21 (building)
    scale = 3, 
    maptype = "terrain", 
    # "terrain", "terrain-background", "terrain-labels", "terrain-lines"
    # source = "google",  # "google", "osm", "stamen", "cloudmademap"
    source = "stamen",  # "google", "osm", "stamen", "cloudmademap"
    color = "color", 
    crop = TRUE
)
ggmap(tokyo.s3)
```

```{r}
tokyo.s4 <- get_map(
    location = loc.base, 
    zoom = 5,  # 3 (continent) to 21 (building)
    scale = 3, 
    maptype = "terrain", 
    # "terrain", "terrain-background", "terrain-labels", "terrain-lines"
    # source = "google",  # "google", "osm", "stamen", "cloudmademap"
    source = "stamen",  # "google", "osm", "stamen", "cloudmademap"
    color = "color", 
    crop = TRUE
)
ggmap(tokyo.s4)
```

## Central Tokyo
```{r}
admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
) %>% rmapshaper::ms_filter_islands(min_area = 1e8) %>% 
    st_transform(crs = crs.base)


admin.code <- readxl::read_excel(
    "input/AdminiBoundary_CD.xlsx", skip = 1
) %>% rename("District" = "行政区域コード")

admin.sf <- admin.sf %>% 
    rename(District = N03_007) %>% 
    select(District) %>%
    group_by(District) %>%
    summarise(.groups = "drop") %>%
    left_join(admin.code %>% select(District, City), by = "District") %>% 
    filter(District <= 13123) %>% 
    summarise(.groups = "drop") %>% 
    sfheaders::sf_remove_holes()

admin.df <- fortify(admin.sf)
```


# Viz {.tabset .tabset-fade .tabset-pills}
```{r}
col.bg <- "gray95"
# col.bg <- "#092532"
# col.bg <- "#262A33"
col.fg <- "#393F4D"

p.1 <- ggmap(tokyo.s1) + 
    labs(
        title = NULL, 
        subtitle = NULL, 
        x = NULL, y = NULL, 
        # caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    geom_sf(inherit.aes = FALSE,
            data = admin.df,
            color = col.sl,
            # linetype = "21",
            size = 1, fill = NA, alpha = 0.5) +
    theme(
        title = element_text(
            face = "bold.italic", color = col.sl, size = 12
        ), 
        plot.subtitle = element_text(
            face = "bold.italic", color = col.sl, size = 10
        ), 
        plot.caption = element_text(color = col.sl, size = 7), 
        text = element_text(face = "bold", color = col.c.b), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        legend.title = element_blank(),
        legend.text = element_text(face = "bold.italic", color = col.c.b), 
        legend.position = c(0.6, 1.075), 
        legend.key.size = unit(0.015, "npc")
    )
p.1
```

```{r}
p.2 <- ggmap(tokyo.s2) + 
    labs(
        title = NULL, 
        subtitle = NULL, 
        x = NULL, y = NULL, 
        # caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    geom_sf(inherit.aes = FALSE,
            data = admin.df,
            color = col.sl,
            # linetype = "21",
            size = 1, fill = NA, alpha = 0.5) +
    theme(
        title = element_text(
            face = "bold.italic", color = col.sl, size = 12
        ), 
        plot.subtitle = element_text(
            face = "bold.italic", color = col.sl, size = 10
        ), 
        plot.caption = element_text(color = col.sl, size = 7), 
        text = element_text(face = "bold", color = col.c.b), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        legend.title = element_blank(),
        legend.text = element_text(face = "bold.italic", color = col.c.b), 
        legend.position = c(0.6, 1.075), 
        legend.key.size = unit(0.015, "npc")
    )
p.2
```

```{r}
p.3 <- ggmap(tokyo.s3) + 
    labs(
        title = NULL, 
        subtitle = NULL, 
        x = NULL, y = NULL, 
        # caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    geom_sf(inherit.aes = FALSE,
            data = admin.df,
            color = col.sl, 
            fill = col.sl, 
            # linetype = "21",
            size = 0.1, alpha = 0.5) +
    theme(
        title = element_text(
            face = "bold.italic", color = col.sl, size = 12
        ), 
        plot.subtitle = element_text(
            face = "bold.italic", color = col.sl, size = 10
        ), 
        plot.caption = element_text(color = col.sl, size = 7), 
        text = element_text(face = "bold", color = col.c.b), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        legend.title = element_blank(),
        legend.text = element_text(face = "bold.italic", color = col.c.b), 
        legend.position = c(0.6, 1.075), 
        legend.key.size = unit(0.015, "npc")
    )
p.3
```

```{r}
p.4 <- ggmap(tokyo.s4) + 
    labs(
        title = NULL, 
        subtitle = NULL, 
        x = NULL, y = NULL, 
        # caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    # geom_sf(inherit.aes = FALSE,
    #         data = admin.df,
    #         color = col.sl, 
    #         fill = col.sl, 
    #         # linetype = "21",
    #         size = 0.1, alpha = 0.5) +
    theme(
        title = element_text(
            face = "bold.italic", color = col.sl, size = 12
        ), 
        plot.subtitle = element_text(
            face = "bold.italic", color = col.sl, size = 10
        ), 
        plot.caption = element_text(color = col.sl, size = 7), 
        text = element_text(face = "bold", color = col.c.b), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        legend.title = element_blank(),
        legend.text = element_text(face = "bold.italic", color = col.c.b), 
        legend.position = c(0.6, 1.075), 
        legend.key.size = unit(0.015, "npc")
    )
p.4
```

```{r}
(p.1 + p.2 ) / (p.3 + p.4) + 
    patchwork::plot_annotation(
        caption = "#30DaysMapChallenge; @Maxwell_110", 
        theme = theme(plot.caption = element_text(size = 10, color = col.os))
    )
ggsave("fig/Scale.jpg", width = 10, height = 10)
```

