---
title: "Smile Vignettes 01"
subtitle: "1. Converting of sf objects to spm"
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 10
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```
See vignette vol.1:  
https://lcgodoy.me/smile/articles/sf-to-spm.html

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(smile)  # geospatial analysis
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping

source(file = "utility/helper_functions.R")
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
col.tw <- rgb(219, 215, 210, maxColorValue = 255)  # TimberWolf
col.os <- rgb(65, 74, 76, maxColorValue = 255)     # Outer Space
col.rp <- rgb(120, 81, 169, maxColorValue = 255)   # Royal Purple
col.mb <- rgb(26, 72, 118, maxColorValue = 255)    # Midnight Blue
col.pb <- rgb(28, 169, 201, maxColorValue = 255)   # Pacific Blue
col.cb <- rgb(176, 183, 198, maxColorValue = 255)  # Cadet Blue
col.el <- rgb(206, 255, 29, maxColorValue = 255)   # Electric Lime
col.cg <- rgb(0, 204, 153, maxColorValue = 255)    # Caribbean Green
col.mt <- rgb(255, 130, 67, maxColorValue = 255)   # Mango Tango
col.rm <- rgb(227, 37, 107, maxColorValue = 255)   # RazzMatazz
col.sl <- rgb(252, 40, 71, maxColorValue = 255)    # ScarLet
col.plos.yellow <- rgb(214, 225, 61, maxColorValue = 255)   # PLOS Yellow
col.plos.pink <- rgb(207, 0, 163, maxColorValue = 255)      # PLOS Pink
col.bmc.gray <- rgb(255, 253, 246, maxColorValue = 255)   # BMC Gray
col.bmc.purple <- rgb(191, 18, 248, maxColorValue = 255)  # BMC Purple
col.bmc.navy <- rgb(26, 46, 79, maxColorValue = 255)      # BMC Navy Blue
col.bmc.blue <- rgb(1, 74, 129, maxColorValue = 255)      # BMC Blue
col.bmc.sky <- rgb(15, 153, 190, maxColorValue = 255)     # BMC Sky Blue
col.bmc.green <- rgb(0, 73, 64, maxColorValue = 255)      # BMC Deep Green
col.bmc.pink <- rgb(239, 37, 95, maxColorValue = 255)     # BMC Pink

font.base <- "Candara"
# font.base <- "Times New Roman"
theme_set(theme_minimal(base_family = font.base))
options(dplyr.summarise.inform = TRUE)

# Twitter Logo and Account
# Usage: add a code line below
# annotation_custom(grob = icon.grob, xmin = 1, xmax = 1, ymin = 1, ymax = 1)
# +
# annotate(geom = "text", x = 1, y = 1, label = "@Maxwell_110", 
# alpha = 0.5, size = 4, family = "Candara", color = col.tw)
icon.arr <- png::readPNG("fig/twitter.png")
icon.grob <- grid::rasterGrob(icon.arr, 
                              width = unit(1.20 * 3, "cm"), 
                              height = unit(0.99 * 3, "cm"), 
                              interpolate = FALSE)
```


# Dataset {.tabset .tabset-fade .tabset-pills}
## Vignette
```{r Vignette}
data("liv_lsoa")
data("liv_msoa")
```

https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L01-v3_1.html

Land Price Open Dataset
  
L01_006/_100: Price (JPY/m$^{2}$)  
L01_007: Price Change (%)  
L01_022: District Code  
L01_023: City  
L01_024: Address  

# Tokyo
```{r Tokyo}
admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
) %>% rmapshaper::ms_filter_islands(min_area = 1e8)

lp.sf <- sf::read_sf("input/Land-Price_Tokyo_2022/L01-22_13.shp")

# print(st_crs(admin.sf))  # JGD2011
# print(st_crs(lp.sf))  # JGD2000

admin.sf <- admin.sf %>% st_transform("+proj=longlat +ellps=WGS84")
lp.sf <- lp.sf %>% st_transform("+proj=longlat +ellps=WGS84")
```



# References
Powered by ZOTERO  

