---
title: "lme4 convergence problem"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
output: 
   html_document:
      number_sections: TRUE
      fig_caption: TRUE
      toc: TRUE
      toc_depth: 5
      toc_float: TRUE
      theme:
         bootswatch: minty
         # bootswatch: cosmo
      highlight: tango
      code_folding: show
      # code_download: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = "../..")
```

I sometimes encountered a convergence problem with mle4 package.
Here I will examine the experiment by following guidance:  
https://m-clark.github.io/posts/2020-03-16-convergence/#remove-zero-random-effects

# Preparations {.tabset .tabset-fade .tabset-pills}

## Load libraries
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"
library(naniar)
library(gtsummary)
library(lme4)
library(lmerTest)
library(coefplot)
library(mixedup)

source("utility/helper_functions.R")
```

## Environment
```{r Environment}
# rgb(73, 81, 112, maxColorValue = 255): "#495170"
col.1 <- "#495170"  # blue
col.2 <- "#f7be16"  # yellow
col.3 <- "#fa8072"  # red
scale.col.1 <- c(col.1, col.3)
font.1 <- "Candara"
theme_set(theme_bw(base_family = font.1))
options(dplyr.summarise.inform = TRUE)
```

# Load DataSets {.tabset .tabset-fade .tabset-pills}
```{r Load DataSets}
df <- readRDS("input/convergence.RDS")
df = df %>% 
   mutate(
      SUR.ID = factor(SUR.ID), 
      replicate = factor(replicate),
      Unit = factor(1:n())
   )
```
