---
title: "Bayes Factor"
subtitle: "based on Okada. 2014 (http://team1mile.com/sjpr61-1/okada.pdf)"
author: "Maxwell"
date: '`r Sys.Date()`'
output: 
   html_document:
      number_sections: true
      fig_caption: true
      toc: true
      toc_depth: 5
      toc_float: true
      theme: cosmo
      highlight: tango
      code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Load libraries
```{r, echo=TRUE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(DT)
library(stringr)
library(lubridate)
library(Lock5Data)

# Visualisation
library(ggplot2)
library(patchwork)
library(broman)
library(gtsummary)
library(summarytools)
library(leaflet)  # map

# Interactivity
library(plotly)
library(crosstalk)

# Parallel
library(purrr)
library(foreach)
library(doParallel)

# Statiscis Analysis
library(psych)
library(naniar)
library(lme4)
library(lmerTest)
library(coefplot)

library(rstan)
library(bayesplot)

library(broom)
library(broom.mixed)

# Custom Functions
source("./utility/helper_functions.R")
```

# Load DataSets {.tabset .tabset-fade .tabset-pills}
Lock5Data::LightatNight
```{r}
data <- LightatNight4Weeks
view.table(data)
```


# Computing Bayes Factor {.tabset .tabset-fade .tabset-pills}
```{r}
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=corei7')
```
```{r}
data.list <- list(
   N = nrow(data),
   d1 = as.integer(data$Light == "LD"),  # light/dark
   d2 = as.integer(data$Light == "DM"),  # dim light at night
   d3 = as.integer(data$Light == "LL"),  # light/light
   Y = data$BMGain
)
```

```{r}
 stan.result <- stan(
     file = ".src/stan/model/BF_model1.stan",
     data = data.list, 
     seed = 2020, 
     chains = 4, 
     iter = 50000,
     warmup = 1000,
     # iter = 10,
     # warmup = 2,
     thin = 1
 )
```

```{r}

```
