---
title: ""
subtitle: ""
author: ""
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
output: 
   html_document:
      number_sections: TRUE
      fig_caption: TRUE
      toc: TRUE
      toc_depth: 5
      toc_float: TRUE
      theme:
         bootswatch: minty
         # bootswatch: cosmo
      highlight: espresso
      # espresso, tango, zenburn
      code_folding: show
      # code_download: TRUE
      fig_width: 10
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

# Preparations {.tabset .tabset-fade .tabset-pills}

## R Packages
```{r, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer

# Parallel
library(purrr)
library(foreach)
library(doParallel)

# Descriptive Statistics
library(naniar)
library(psych)
library(gtsummary)

# Multi Level Model
library(lme4)
library(lmerTest)
library(coefplot)

# Stan
library(rstan)
library(bayesplot)
library(broom)
library(broom.mixed)
```

## Environment
```{r Environment}
# rgb(73, 81, 112, maxColorValue = 255): "#495170"
col.os <- "#414a4c"  # Outer Space
col.rp <- "#7851a9"  # Royal Purple
col.cb <- "#b0b7c6"  # Cadet Blue
col.el <- "#ceff1d"  # Electric Lime
col.rm <- "#e3256b"  # Razzmatazz
col.plos.ye <- "#D6E13D"  # PLOS ONE
scale.col.1 <- c()
theme_set(theme_minimal(base_family = "Candara"))
options(dplyr.summarise.inform = TRUE)
# Twitter Logo and Acc
t.img <- png::readPNG("fig/twitter.png")
t.grob <- grid::rasterGrob(t.img, 
                           width = unit(0.4, "cm"), 
                           height = unit(0.4, "cm"),
                           interpolate = FALSE)
```

# Load DataSets {.tabset .tabset-fade .tabset-pills}
```{r Load DataSets}

```
