---
title: "Bus Stops in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(sfheaders)  # sf_to_df, sf_remove_holes
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
source(file = "utility/geospatial.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()
```


# Dataset {.tabset .tabset-fade .tabset-pills}

https://nlftp.mlit.go.jp/ksj/index.html#koutsuu  
Bus Class Codes: https://nlftp.mlit.go.jp/ksj/gml/codelist/BusClassCd.html  

```{r Dataset}
crs.base <- "+proj=longlat +datum=WGS84"

admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
) %>% rmapshaper::ms_filter_islands(min_area = 1e8) %>% 
    st_transform(crs.base)

admin.code <- readxl::read_excel(
    "input/AdminiBoundary_CD.xlsx", skip = 1
) %>% rename("District" = "行政区域コード")

# tokyo.sf <- readRDS(file = "input/Tokyo_2022/tokoy.sf.RDS")


stop.sf <- sf::read_sf(
    "input/Bus_Stop_Tokyo/P11-10_13-jgd-g_BusStop.shp"
) %>% st_set_crs(crs.base)
# View(stop.sf %>% select(P11_003_1) %>% sfheaders::sf_to_df(fill = TRUE))

root.sf <- sf::read_sf(
    "input/Bus_Root_Tokyo/N07-11_13.shp"
) %>% st_set_crs(crs.base) %>% st_zm()
# View(root.sf %>% select(P11_003_1) %>% sfheaders::sf_to_df(fill = TRUE))
```


# Preprocessing
```{r}
admin.sf <- admin.sf %>% 
    rename(District = N03_007) %>% 
    select(District) %>% 
    filter(District <= 13123) %>% 
    group_by(District) %>% 
    summarise(.groups = "drop") %>% 
    left_join(admin.code %>% select(District, City), by = "District")

admin.agg.sf <- admin.sf %>% 
    select(District) %>% 
    summarise(.groups = "drop") %>% 
    sf_remove_holes()

# plot(admin.agg.sf)
```

## Filter with Polygons for Central Tokyo
```{r}
stop.sf <- stop.sf %>% mutate(
    is.Central = as.numeric(st_within(stop.sf$geometry, admin.agg.sf$geometry))
) %>% 
    filter(!is.na(is.Central)) %>% 
    select(-is.Central)

# root.sf <- root.sf %>% mutate(
#     is.Central = as.numeric(st_within(root.sf$geometry, admin.agg.sf$geometry))
# ) %>% 
#     filter(!is.na(is.Central)) %>% 
#     select(-is.Central)
```


# Viz
```{r}
col.bg <- "#262A33"
col.fg <- "#393F4D"

p1 <- ggplot() + 
    geom_sf(data = admin.sf %>% filter(District <= 13123), 
            size = 0.1, fill = col.fg, color = col.bg) + 
    geom_sf(data = stop.sf %>% select(P11_001), 
            color = col.pr.pink, size = 0.15, alpha = 0.5) + 
    geom_sf(data = root.sf %>% select(N07_001), 
            color = col.bmc.pink, size = 0.4, alpha = 0.3) + 
    lims(x = c(139.54, 139.94), y = c(35.5, 35.84)) + 
    # facet_wrap(vars(INOUT_CAT), nrow = 2) + 
    labs(title = "Bus Stops and Roots in Central Tokyo", 
         subtitle = NULL, 
         caption = "#30DaysMapChallenge; @Maxwell_110", 
         x = NULL, y = NULL) + 
    theme(
        title = element_text(
            # family = "Times New Roman", 
            color = col.bmc.pink, size = 13
        ), 
        plot.title = element_text(hjust = 0, vjust = -2), 
        plot.subtitle = element_text(
            # family = "Times New Roman", face = "plain", 
            color = col.bmc.pink, size = 10, 
            # margin = margin(t = 35, r = -00, b = -35, l = 00, unit = "pt")
        ), 
        plot.caption = element_text(
            # family = "Times New Roman", 
            color = col.bmc.pink, size = 7
        ), 
        text = element_text(face = font.face), 
        axis.text = element_blank(), 
        strip.text = element_text(
            face = "bold.italic", color = col.bmc.pink, size = 15
        ), 
        strip.switch.pad.wrap = unit(0.1, "npc"), 
        legend.position = c(0.7, 0.15), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid = element_line(colour = col.bg), 
    )

p1

ggsave("fig/30DaysMapChallenge_2022/Bus.jpg", width = 4, height = 5)
```
