---
title: "Fishing port in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(pals)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)

library(ggmap)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
source(file = "utility/geospatial.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()

# https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
crs.base <- "+proj=longlat +datum=WGS84"
register_google(key = readRDS(file = "api/google-api.RDS"))
loc.base <- c(lon = 139.73, lat = 35.70)
```


# Dataset
## Load
### Basic Dataset
```{r}
ne.jpn.sf <-
    rnaturalearth::ne_states(country = "Japan", returnclass = "sf") %>% 
    rmapshaper::ms_filter_islands(min_area = 1e10)  # remove small islands

pref.name.codes.df <- 
    read.csv("input/prefecture-codes.csv", encoding = "cp932")
```

### Fishing Ports
https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-C09.html
```{r}
fp.sf <- read_sf("input/Fishing_Port_2006/C09-06_FishingPort.shp") %>% 
    select(C09_003) %>% 
    rename(Codes = C09_003) %>% 
    mutate(
        Codes = formatC(Codes, width = 5, flag = "0"), 
        Codes = as.integer(str_sub(Codes, start = 1, end = 2))
    )

st_crs(fp.sf) <- crs.base
```

## Preprocessing
```{r}
fp.sf <- fp.sf %>% left_join(pref.name.codes.df, 
                             by = c("Codes" = "No"))

fp.sf.n <- sfheaders::sf_to_df(fp.sf, fill = TRUE) %>%
    group_by(Prefecture_En) %>% summarise(N = n()) %>% 
    arrange(desc(N))
```

```{r}
ne.jpn.sf <- ne.jpn.sf %>% 
    select(iso_3166_2, name, region, latitude, longitude) %>% 
    mutate(
        longitude = ifelse(name == "Nagasaki", 129.8, longitude), 
        latitude = ifelse(name == "Nagasaki", 33.1, latitude), 
        longitude = ifelse(name == "Kagoshima", 130.5, longitude), 
        latitude = ifelse(name == "Kagoshima", 31.6, latitude), 
    ) %>% 
    tibble::new_tibble(nrow = nrow(.), class = "sf") %>% 
    left_join(fp.sf.n, by = c("name" = "Prefecture_En")) %>% 
    arrange(iso_3166_2)
glimpse(ne.jpn.sf)
```


# Viz {.tabset .tabset-fade .tabset-pills}

## Draw
```{r}
# col.bg <- "gray95"
# col.bg <- "#092532"
col.bg <- "#262A33"
col.fg <- "#393F4D"
arrow <- arrow.df(xb = 139.58, yb = 35.55, len = 0.015)
label.df <- data.frame(x = 139.58, y = 35.582, lab = "N")

p <- ggplot(data = ne.jpn.sf) + 
    geom_sf(mapping = aes(), fill = col.fg, alpha = 0.8, 
            size = 0.05, color = "gray50") + 
    annotate(
        geom = "text", 
        x = 128.5, y = 43, 
        label = "Fishing ports are especially concentrated in Hokkaido \nand Nagasaki Prefecture in Japan. \nJapan is famous for `Sushi`, and in areas where \nthere are many fishing ports, you can enjoy \ndelicious sushi at a reasonable price.\nMy reccomendation is Sapporo in Hokkaido :)",
        hjust = 0,
        color = col.bmc.sky, size = 3, family = "Times New Roman"
    ) + 
    annotate(
        geom = "text", 
        x = 129, y = 40.5 - 0.5, 
        label = "Hokkaido: 290 ports",
        hjust = 0,
        color = col.el, size = 3, family = "Candara"
    ) + 
    geom_sf(
        data = ne.jpn.sf %>% filter(name == "Hokkaido"), 
        mapping = aes(), fill = col.el, alpha = 0.3, 
        size = 0.05, color = NA
    ) + 
    annotate(
        geom = "text", 
        x = 129, y = 39.25 - 0.5, 
        label = "Nagasaki: 288 ports\n...",
        hjust = 0,
        color = col.sl, size = 3, family = "Candara"
    ) + 
    geom_sf(
        data = ne.jpn.sf %>% filter(name == "Nagasaki"), 
        mapping = aes(), fill = col.sl, alpha = 0.7, 
        size = 0.05, color = NA
    ) + 
    geom_sf(
        data = ne.jpn.sf %>% filter(name == "Tokyo"), 
        mapping = aes(), fill = col.bmc.green.l, alpha = 0.3, 
        size = 0.05, color = NA
    ) + 
    annotate(
        geom = "text", 
        x = 129, y = 37.75 - 0.5, 
        label = "Tokyo: 25 ports\n...",
        hjust = 0,
        color = col.bmc.green.l, size = 3, family = "Candara"
    ) + 
    labs(title = "Fishing Ports in Japan", 
         caption = "#30DaysMapChallenge; @Maxwell_110", 
         x = NULL, y = NULL) + 
    geom_sf(mapping = aes(size = 1), data = fp.sf, 
            size = 0.2, color = col.bmc.sky, alpha = 0.5) + 
    lims(x = c(128, 145), y = c(31, 45)) + 
    guides(size = guide_legend(title = NULL, keyheight = 0.5)) + 
    theme(
        title = element_text(family = "Times New Roman", face = "bold", 
                             color = col.bmc.sky, size = 12), 
        text = element_text(face = font.face, color = col.bmc.sky), 
        axis.text = element_blank(), 
        legend.position = c(0.25, 0.7), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.title = element_text(
            hjust = 0.1, 
            margin = margin(t = 10, r = -00, b = -10, l = 00, unit = "pt")
        ), 
        plot.subtitle = element_text(
            color = col.tw, size = 9, 
            margin = margin(t = 35, r = -00, b = -35, l = 00, unit = "pt")
        ), 
        plot.caption = element_text(
            family = "Times New Roman", color = col.bmc.sky, size = 5.5
        ), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid = element_line(colour = col.bg), 
    )

p
ggsave("fig/fishing-ports.jpg", width = 6 * 1, height = 6 * 1.2)
```
