---
title: "Islands in Tokyo"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(pals)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)

library(ggmap)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
source(file = "utility/geospatial.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()

# https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
crs.base <- "+proj=longlat +datum=WGS84"
register_google(key = readRDS(file = "api/google-api.RDS"))
loc.base <- c(lon = 139.73, lat = 35.70)
```


# Dataset
```{r}
ne.jpn.sf <-
    rnaturalearth::ne_states(country = "Japan", returnclass = "sf") %>% 
    rmapshaper::ms_filter_islands(min_area = 1e10)  # remove small islands

admin.sf <- sf::read_sf(
    "input/Administrative_district_Tokyo_2021/N03-21_13_210101.shp"
)
```

# Preprocessing
```{r}
```

# Viz {.tabset .tabset-fade .tabset-pills}
## Draw
```{r}
# col.bg <- "gray95"
# col.bg <- "#092532"
col.bg <- "#262A33"
col.fg <- "#393F4D"
arrow <- arrow.df(xb = 132, yb = 40, len = 0.75)
label <- data.frame(x = 132, y = 42, lab = "N")
box.ogasawara.all.df <- 
    data.frame(xmin = 139, ymin = 24, xmax = 143.5, ymax = 28.5)
box.ogasawara.main.df.1 <- 
    data.frame(xmin = 141.5, ymin = 26.3, xmax = 143, ymax = 27.3)
box.ogasawara.main.df.2 <- 
    data.frame(xmin = 147.5, ymin = 23, xmax = 163.5, ymax = 44)

p.ogasawara <- ggplot() + 
    geom_sf(data = admin.sf %>% 
                select(N03_004) %>% 
                filter(N03_004 == "小笠原村"), 
            fill = col.bmc.pink, alpha = 0.5, 
            color = col.bmc.pink, size = 0.25) + 
    lims(x = c(142.05, 142.3), y = c(26.5, 27.23)) + 
    theme(
        axis.text = element_blank(), 
        panel.grid = element_blank(), 
        panel.grid.major = element_blank()
    )
# p.ogasawara
p.ogasawara.plot <- data_frame(
    x = c(157), y = c(34), 
    width = 16, height = 23, plot = list(p.ogasawara)
)

p <- ggplot() + 
    geom_sf(data = ne.jpn.sf %>% select(name), 
            fill = col.fg, alpha = 0.75, 
            color = col.bg, size = 0.2) + 
    lims(x = c(129, 164), y = c(20, 46)) + 
    geom_sf(data = admin.sf %>% select(N03_004), 
            fill = col.bmc.pink, alpha = 0.9, 
            color = col.bmc.pink, size = 0.25) + 
    annotate(geom = "text", 
             x = 139.65, y = 36.4, label = "Tokyo", 
             color = col.bmc.pink, family = "Times New Roman", size = 2) + 
    geom_rect(
        data = box.ogasawara.all.df, 
        mapping = aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
        color = col.bmc.pink, size = 0.2, fill = NA
    ) + 
    annotate(geom = "text", 
             x = 141.25, y = 29.0, label = "Ogasawara Islands", 
             color = col.bmc.pink, family = "Times New Roman", size = 2) + 
    annotate(geom = "text", 
             x = 130, y = 30, 
             label = "Many of the islands belong to Tokyo, \nand the southernmost island is \nfar below the mainland.", 
             hjust = 0, 
             color = col.tw, family = "Times New Roman", size = 2) + 
    geom_rect(
        data = box.ogasawara.main.df.1, 
        mapping = aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
        color = "#937DC2", size = 0.3, fill = NA
    ) + 
    geom_subview(
        data = p.ogasawara.plot, 
        mapping = aes(x = x, y = y, 
                      subview = plot, width = width, height = height)
    ) + 
    geom_rect(
        data = box.ogasawara.main.df.2, 
        mapping = aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
        color = "#937DC2", size = 0.5, fill = NA
    ) + 
    geom_curve(
        aes(x = x1, y = y1, xend = x2, yend = y2),
        data = data.frame(x1 = 143.2, x2 = 147.3, y1 = 26.5, y2 = 27), 
        arrow = arrow(length = unit(0.02, "npc"), type = "open"), 
        lineend = "round", color = "#937DC2", size = 0.5
    ) + 
    annotate(geom = "text", 
             x = 153, y = 41, label = "Chichi \nIslands", 
             color = "#937DC2", family = "Times New Roman", size = 3) + 
    annotate(geom = "text", 
             x = 152, y = 28, label = "Haha \nIslands", 
             color = "#937DC2", family = "Times New Roman", size = 3) + 
    annotate(geom = "text", 
             x = 129, y = 21, 
             label = "The Ogasawara Islands are registered as a World Natural Heritage site, \nand although it takes about a day by ship from the mainland, the islands are very rich in nature.", 
             hjust = 0, 
             color = "#937DC2", family = "Times New Roman", size = 3) + 
    annotate(geom = "text", 
             x = 155, y = 35, 
             label = "The Ogasawara Islands mainly comprise \nChichijima and Hahajima.", 
             # hjust = 0, 
             color = "#937DC2", family = "Times New Roman", size = 2) + 
    geom_polygon(aes(x = aX, y = aY), data = arrow, fill = col.tw) + 
    geom_text(aes(x = x, y = y, label = lab), 
              data = label, color = col.tw, size = 4, 
              family = "Times New Roman") + 
    labs(
        title = "Ogasawara Islands in Tokyo", 
        subtitle = NULL, 
        x = NULL, y = NULL, 
        caption = "#30DaysMapChallenge; @Maxwell_110"
    ) + 
    theme(
        title = element_text(
            family = "Times New Roman", face = "bold", 
            color = col.tw, size = 14
        ), 
        plot.title = element_text(hjust = 0.05, vjust = 0), 
        plot.subtitle = element_text(
            family = "Times New Roman", face = "bold", 
            color = col.tw, size = 10, 
            hjust = 0, vjust = 0
        ), 
        plot.caption = element_text(color = col.tw, size = 6), 
        text = element_text(family = "Times New Roman", color = col.tw), 
        # axis.text = element_text(family = font.base, face = "italic", 
        #                          color = col.c.b, size = 4), 
        axis.text = element_blank(), 
        plot.background = element_rect(fill = col.bg, color = col.bg), 
        # plot includes panel
        # panel.background = element_rect(fill = col.bg, color = col.bg),
        panel.grid = element_blank(), 
        panel.grid.major = element_blank(), 
        strip.text = element_blank(), 
        # legend
        # legend.title = element_blank(),
        # legend.text = element_text(
        #     family = "Times New Roman", face = "plain", 
        #     color = col.c.b, 
        #     size = 5
        # ), 
        legend.position = c(0.875, 0.175), 
        legend.key.size = unit(0.015, "npc")
    )

p

ggsave("fig/30DaysMapChallenge_2022/Islands.jpg", width = 5, height = 5.5)
```
