---
title: "Landslide Disaster Map in Japan"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer
library(rnaturalearth)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
ls.sf <- sf::read_sf(
    "input/Landslide_Tokyo_2010/A26-10_13-g_SedimentDisasterHazardArea_Surface.shp"
)
sf::st_crs(ls.sf) <- "+proj=longlat +datum=WGS84"
```


# Viz
```{r}
m <- leaflet(data = ls.sf) %>%
    addProviderTiles(
        provider = "OpenStreetMap.HOT", 
        # provider = "CartoDB.PositronNoLabels", 
        options = providerTileOptions(opacity = 0.5)
    ) %>% 
    setView(lng = 139.700, lat = 35.695, zoom = 15) %>%
    addPolygons(
        fillColor = col.sl, fillOpacity = .5, 
        stroke = TRUE, color = col.bmc.blue, 
        weight = 1.0, dashArray = "1", opacity = .25 
    )
m
```


# References


