---
title: "bonsai"
subtitle: "vignettes"
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

------------------------------------------------------------------------

# Preparations {.tabset .tabset-fade .tabset-pills}

## Packages

```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# ML
library(tidymodels)
library(bonsai)
tidymodels::tidymodels_prefer()  # override conflicting methods of other pkgs
```

## Environment

```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
# icon.grob <- png_to_grob()

theme_update(panel.grid.minor = element_blank())
```

# Dataset {.tabset .tabset-fade .tabset-pills}

```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
glimpse(penguins)
```

```{r}
view.table(penguins)
```

# Missing Pattern

```{r}
p <- ggmice::plot_pattern(data = penguins, 
                          vrb = "all", square = TRUE, 
                          rotate = FALSE, cluster = NULL)
p + theme_minimal(base_family = font.base) + 
    theme(panel.grid = element_blank())
```

# Conditional Randomom Forests

@hothorn2006

```{r}
rf_mod <- rand_forest() %>% 
    set_engine(engine = "partykit") %>% 
    set_mode(mode = "classification") %>% 
    fit(formula = species ~ flipper_length_mm + island, 
        data = penguins)
```

# LGBM

```{r}
bt_mod <- boost_tree() %>% 
    set_engine(engine = "lightgbm") %>% 
    set_mode(mode = "classification") %>% 
    fit(formula = species ~ flipper_length_mm + island, 
        data = penguins)
```

# References
