---
title: "Case Study"
subtitle: "01: insuranceData"
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
# link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

----

# Preparations {.tabset .tabset-fade .tabset-pills}

## Packages

```{r Packages, echo=TRUE, message=FALSE}
# Data manipulation
library(tidyverse)
# library(data.table)
# library(janitor)  # janitor::row_to_names()
# library(DT)
# library(stringr)
# library(lubridate)

# Visualisation
# library(ggplot2)
# library(ggalt)  # geom_encircle
# library(patchwork)
# library(broman)  # plot_crayons()
# library(ggsci)  # Journal palette
# library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
# library(extrafont)  # "Candara"
# library(dotwhisker)

# Descriptive Statistics
# library(mice)
# library(ggmice)  # see src/imputation/ggmice_XX.Rmd
# library(psych)
library(skimr)
# library(gtsummary)
library(summarytools)

# ML
library(tidymodels)
# library(broom.mixed)
tidymodels::tidymodels_prefer()  # override conflicting methods of other pkgs

# Dataset
library(insuranceData)
```

## Environment

```{r Environment, echo=TRUE, message=FALSE}
# source(file = "utility/environments.R")
# source(file = "utility/helper_functions.R")
```

# Dataset {.tabset .tabset-fade .tabset-pills}
```{r}
data("dataCar")
glimpse(dataCar)
?dataCar
```

# Simple EDA {.tabset .tabset-fade .tabset-pills}
```{r}
dataCar %>% skimr::skim()
dataCar %>% dfSummary() %>% stview(file = "output/case-study_01.html")
```

# Data splitting and resampling {.tabset .tabset-fade .tabset-pills}
```{r}
set.seed(2023)
init_splits <- initial_split(dataCar, prop = 0.8, strata = clm)
```
```{r}
car_train_val <- training(init_splits)
car_test <- testing(init_splits)
```

