---
title: "timetk vignettes"
subtitle: ""
author: ""
date: '`r Sys.Date()`'
# bibliography: references.bib
# link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)  # in tidyverse
library(lubridate)  # in tidyverse

# Visualisation
library(ggplot2)  # RColorBrewer::display.brewer.all()
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(PrettyCols)  # view_all_palettes(colourblind_friendly = TRUE)
library(extrafont)  # fonttable(); "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)  # tbl_summary; tbl_regression; https://cran.r-project.org/web/packages/gtsummary/vignettes/tbl_regression.html

# Time Series
library(timetk)
library(tsibble)  # https://otexts.com/fpp3/index.html
library(fable)  # https://otexts.com/fpp3/index.html
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
set.seed(2023)

source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "timetk_"
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
walmart_sales_weekly
```


# Time Series features
```{r}
# Custom Function
mean.na <- function(x, na.rm = TRUE) {
    mean(x, na.rm = na.rm)
}

tsfeature_tbl <- walmart_sales_weekly %>%
    group_by(id) %>%
    tk_tsfeatures(
        .date_var = Date, 
        .value    = Weekly_Sales, 
        .period   = 52, 
        .features = c(
            "frequency", 
            "stl_features", 
            "entropy", 
            "acf_features", 
            "mean.na"
        ),
        .scale    = TRUE, 
        .trim = FALSE, 
        .parallel = FALSE, 
        .na_action = na.pass, 
        .prefix   = "ts_"
    ) %>%
    ungroup()

tsfeature_tbl
```


# Clustering w/ K-Means
```{r}
cluster_tbl <- tibble(
    cluster = tsfeature_tbl %>%
        select(-id) %>%
        as.matrix() %>%
        kmeans(centers = 3, nstart = 100) %>%
        pluck("cluster")
) %>% bind_cols(tsfeature_tbl)

cluster_tbl
```


# Viz
```{r}
cluster_tbl %>% 
    select(cluster, id) %>%
    right_join(walmart_sales_weekly, by = "id", multiple = "all") %>%
    group_by(id) %>%
    plot_time_series(
        Date,
        Weekly_Sales,
        .color_var   = cluster,
        .facet_ncol  = 2,
        .interactive = FALSE
    ) + theme_minimal(base_family = font.base) + 
    theme(
        title = element_text(size = 20)
    )
```


# References
