---
title: "ggpackets"
subtitle: ""
author: ""
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

library(ggpackets)

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")
# icon.grob <- png_to_grob()

theme_update(panel.grid.minor = element_blank())
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
```


# Quick Start
```{r}
ggpk_box_and_scatter <- ggpacket() +
    geom_point(position = position_jitter(width = 0.2), alpha = 0.5) + 
    geom_boxplot(outlier.shape = NA, fill = NA, color = col.os)

codes = "1. Sets ggplot layer together:
    ggpk_box_and_scatter <- ggpacket() + 
        geom_point(position = position_jitter(width = 0.2), alpha = 0.5) + 
        geom_boxplot(outlier.shape = NA, fill = NA, color = col.os)

2. Add ggpacket class object to ggplot function:
    ggplot(penguins, aes(x = species, y = body_mass_g, color = sex)) + 
        ggpk_box_and_scatter()"

ggplot(penguins, aes(x = species, y = body_mass_g, color = sex)) + 
    ggpk_box_and_scatter() + 
    labs(
        x = "Penguin species", y = "Body mass (g)", 
        title = "ggplot using ggpacket: using penguin dataset", 
        subtitle = codes, caption = "@ Maxwell_110"
    ) + 
    theme(
        axis.title = element_text(size = 12, color = col.os), 
        plot.title = element_text(size = 15, color = col.os), 
        plot.caption = element_text(size = 10, color = "gray"), 
        plot.subtitle = element_text(
            size = 8, 
            margin = margin(t = 20, b = -90),
            color = col.plos.pink
        ), 
        axis.text = element_text(size = 12, color = col.os)
    )

ggsave("fig/ggpacket_1.jpg", width = 7, height = 5)
```


# References


