---
title: "arf: Adversarial Random Forests"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
# link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)  # RColorBrewer::display.brewer.all()
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

library(arf)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

font.base <- "Georgia"
fn.prefix <- "arf_vignette"
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
```

```{r}
ggmice::plot_pattern(
    data = penguins, 
    vrb = "all", 
    square = TRUE, 
    rotate = FALSE, 
    cluster = NULL
) + theme_minimal(base_family = font.base)
```

```{r}
penguins <- penguins %>% 
    filter(!is.na(sex)) %>% 
    mutate(
        flipper_length_mm = as.numeric(flipper_length_mm), 
        body_mass_g = as.numeric(body_mass_g)
    )
```

```{r}
glimpse(penguins)
```



# Adversarial Random Forests
```{r}
arf <- arf::adversarial_rf(penguins)
```

```{r}
psi <- arf::forde(arf, penguins)
```

```{r}
mean(arf::lik(arf, psi, penguins))
```

```{r}
synthetic.penguins <- arf::forge(psi, nrow(penguins))
```


# Viz
```{r}
p1 <- ggplot(data = penguins) + 
    geom_point(aes(x = body_mass_g, y = bill_length_mm, 
                   color = species)) + 
    PrettyCols::scale_color_pretty_d(name = "Joyful") + 
    labs(title = "Adversarial Random Forests: arf using Penguin Dataset", 
         subtitle = "Raw Dataset") + 
    theme(
        plot.title = element_text(family = font.base, face = "bold", 
                                  size = 17, vjust = 1), 
        plot.subtitle = element_text(family = font.base, size = 14, 
                                     face = "bold", vjust = -0.5), 
        axis.title.x = element_text(family = font.base,
                                    face = "bold",
                                    size = 15, hjust = 1.2), 
        axis.title.y = element_text(family = font.base,
                                    face = "bold",
                                    size = 15), 
        legend.position = c(0.8, 0.25), 
        legend.title = element_text(family = font.base, 
                                    face = "bold", size = 15), 
        legend.text = element_text(family = font.base, 
                                   face = "bold", size = 10)
    )

p2 <- ggplot(data = synthetic.penguins) + 
    geom_point(aes(x = body_mass_g, y = bill_length_mm, 
                   color = species)) + 
    PrettyCols::scale_color_pretty_d(name = "Joyful") + 
    labs(subtitle = "Synthetic Dataset", 
         caption = "@Maxwell_110") + 
    theme(
        plot.subtitle = element_text(family = font.base, size = 14, 
                                     face = "bold", vjust = -0.5), 
        axis.title = element_blank(), 
        legend.position = "none", 
        legend.title = element_text(family = font.base, 
                                    face = "bold", size = 15), 
        legend.text = element_blank(), 
        plot.caption = element_text(size = 7, color = col.sage.gray)
    )


p1 + p2

ggsave(paste0("fig/", fn.prefix, ".jpg"), dpi = 300, 
       width = 10, height = 5)
```


# References
* https://bips-hb.github.io/arf/
