---
title: "dotwhisker"
subtitle: "Dot-and-Whisker Plots of Regression Results"
author: ""
date: '`r Sys.Date()`'
# bibliography: references.bib
# link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=TRUE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)  # in tidyverse
library(lubridate)  # in tidyverse

# Visualisation
library(ggplot2)  # RColorBrewer::display.brewer.all()
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(PrettyCols)  # view_all_palettes(colourblind_friendly = TRUE)
library(extrafont)  # fonttable(); "Candara"
library(latex2exp)  # example: latex2exp::TeX("Equation: $\\lambda$")
library(showtext)

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)  # tbl_summary; tbl_regression; https://cran.r-project.org/web/packages/gtsummary/vignettes/tbl_regression.html

# ML
library(tidymodels)  # check src/tidymodels files
tidymodels::tidymodels_prefer()  # override conflicting methods of other pkgs

# Multi Level Model
library(lme4)
library(lmerTest)
library(coefplot)  # forest plot
library(dotwhisker)  # forest plot
library(performance)  # Generic R^2, ICC, Over-dispersion, Heteroschedasticity
# library(multilevelmod)
library(ggstats)  # ggcoef_model() for forest plot

# pacman::p_load()
```

## Environment
```{r Environment, echo=TRUE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "dotwhisker_vignette"
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
glimpse(penguins)
```
```{r}
p <- ggmice::plot_pattern(data = penguins, 
                          vrb = "all", square = TRUE, 
                          rotate = FALSE, cluster = NULL)
p + theme_minimal(base_family = font.base) + 
    theme(panel.grid = element_blank())
```


# Basic Usage
## Model fitting
```{r}
m1 <- lm(body_mass_g ~ species + island + sex, 
         data = penguins %>% filter(!is.na(body_mass_g)))
```

## draw a dot-and-whisker plot
```{r}
caption_text  <- str_glue("{x.glue}: @Maxwell_110")
showtext_auto(enable = TRUE)

dwplot(
    x = m1, 
    vline = geom_vline(xintercept = 0, colour = "grey77", linetype = 2, linewidth = 0.2), 
    dot_args = list(size = 2, color = col.pr.orange), 
    whisker_args = list(color = col.pr.orange)
) + 
    labs(
        title = "Dotwhisker plot", 
        subtitle = "Using a penguin dataset with a simple linear model", 
        caption = caption_text
    ) + 
    theme(
        text = element_text(family = font.base.showtext), 
        plot.title = element_text(family = "cinzel", 
                                  color = col.mt, size = 60), 
        plot.subtitle = element_text(family = "cinzel", 
                                     color = col.mt, size = 40), 
        plot.caption = element_markdown(family = font.base.showtext, 
                                        color = col.mt, size = 20), 
        axis.text = element_text(family = font.base.showtext, 
                                 color = col.mt, size = 20),
        plot.background = element_rect(fill = col.bg), 
        panel.grid.major = element_line(color = col.os, size = 0.1), 
        panel.grid.minor = element_blank()
    )
ggsave(str_glue("fig/{fn.prefix}_1.jpg"), width = 8, height = 4.5, dpi = 300)
```

# References
