---
title: "Survival Analysis"
subtitle: "gehan data"
author: "HoxoMaxwell"
date: '`r Sys.Date()`'
output: 
   html_document:
      number_sections: true
      toc: true
      toc_depth: 5
      toc_float: true
      theme: cosmo
      highlight: tango
      code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Load Library
```{r}
library(survival)
library(survminer)
library(MASS)
```

# Load Data
```{r}
data("gehan")
head(gehan)
```

- pair: label for pair
- time: remission time in weeks
- cens: censoring, 0/1
- treat: treatment, control or 6-MP

# Survival Analysis
## Build Survival Time Data Object
```{r}
Surv(gehan$time, gehan$cens)
```
```{r}
ge.sf <- survfit(Surv(time = time, time2 = cens) ~ treat, 
                 data = gehan)
ge.sf
```
```{r, fig.width=10, fig.height=10}
summary(ge.sf)
ggsurvplot(
  fit = ge.sf,
  data = gehan,
  conf.int = T,
  pval = T,
  risk.table = T,
  cumevents = T,
  cumcensor = T,
  tables.height = 0.15
  )
```


