---
title: "Crude Oil Analysis"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
   html_document:
      number_sections: TRUE
      fig_caption: TRUE
      toc: TRUE
      toc_depth: 5
      toc_float: TRUE
      theme:
         bootswatch: minty
         # bootswatch: cosmo
      highlight: espresso
      # espresso, tango, zenburn
      code_folding: show
      # code_download: TRUE
      fig_width: 10
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

# Preparations {.tabset .tabset-fade .tabset-pills}

## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# GeoSpatial Analysis
library(sf)  # simple feature
library(spdep)  # helpful functions for mapping
library(rmapshaper)  # helpful functions for mapping
library(tmap)  # map viewer
library(leaflet)  # map viewer
library(mapview)  # map viewer

# ML
# library(tidymodels)
# tidymodels::tidymodels_prefer()

# Multi Level Model
library(lme4)
library(lmerTest)
library(coefplot)
# library(multilevelmod)

# Stan
library(rstan)
library(bayesplot)
library(broom)
library(broom.mixed)

# Parallel
library(purrr)
library(foreach)
library(doParallel)

source(file = "utility/helper_functions.R")
```

## Environment
```{r Environment}
# rgb(73, 81, 112, maxColorValue = 255)
col.tw <- "#dbd7d2"  # Timberwolf
col.os <- "#414a4c"  # Outer Space
col.rp <- "#7851a9"  # Royal Purple
col.pb <- "#1ca9c9"  # Pacific Blue
col.cb <- "#b0b7c6"  # Cadet Blue
col.el <- "#ceff1d"  # Electric Lime
col.cg <- "#00cc99"  # Caribbean Green
col.mt <- "#ff8243"  # Mango Tango
col.rm <- "#e3256b"  # Razzmatazz
col.sl <- "#fc2847"  # Scarlet
col.plos.yellow <- "#D6E13D"  # PLOS ONE Yellow
col.plos.pink <- "#CF00A3"  # PLOS ONE Pink
col.bg <- "#262A33"
col.fg <- "#393F4D"

font.base <- "Candara"
# font.base <- "Times New Roman"
theme_set(theme_minimal(base_family = font.base))
options(dplyr.summarise.inform = TRUE)
# Twitter Logo and Acc
# Usage: add a code line below
# annotation_custom(grob = icon.grob, xmin = 1, xmax = 1, ymin = 1, ymax = 1)
icon.arr <- png::readPNG("fig/twitter_gray.png")
icon.grob <- grid::rasterGrob(icon.arr, 
                              width = unit(1.20 * 0.3, "cm"), 
                              height = unit(0.99 * 0.3, "cm"), 
                              interpolate = FALSE)
```

# DataSets {.tabset .tabset-fade .tabset-pills}
```{r DataSets}
data <- read_csv("input/2022-05_Commodity.csv", na = c("", "NA", ".."))
```

# Preprocessing
```{r}
data <- data %>% mutate(
    DATE = as.Date(paste0(
        str_replace(DATE, pattern = "M", replacement = "-"), "-01"
    ))
)
```

```{r fig.height=6}
event.l <- list(
    name = c("Lehman\nShock", "COVID-19"), 
    date = as.Date(c("2008-09-15", "2020-01-30")), 
    color = c(col.sl, col.sl)  # col.tw is base.
)

p <- data %>% filter(DATE >= as.Date("2000-01-01")) %>% 
    ggplot() + 
    geom_point(aes(x = DATE, y = CRUDE_WTI), 
               size = 1, color = col.plos.yellow) + 
    geom_line(aes(x = DATE, y = CRUDE_WTI), 
              color = col.plos.yellow, alpha = 0.5) + 
    scale_x_date(date_breaks = "1 years" , date_labels = "%Y") + 
    labs(x = NULL, y = NULL, title = "Timeline of WTI Crude Oil Price") + 
    theme(
        title = element_text(color = col.el, size = 20), 
        axis.text = element_text(color = col.plos.yellow), 
        legend.position = c(0.85, 0.15), 
        legend.title = element_text(size = 10), 
        legend.text = element_text(color = col.tw), 
        # plot.margin = unit(c(0, 0, 0, 0), "pt"), 
        plot.title = element_text(
            margin = margin(t = 15, r = -50, b = -15, l = 50, unit = "pt")
        ), 
        plot.background = element_rect(fill = col.bg), 
        # plot includes panel
        panel.background = element_rect(fill = col.bg, color = col.bg), 
        panel.grid.major = element_line(color = col.os, size = 0.1), 
        panel.grid.minor = element_blank(), 
    ) + 
    annotation_custom(grob = icon.grob, 
                      xmin = as.Date("2019-7-01"), 
                      xmax = as.Date("2019-7-01"), 
                      ymin = 125, ymax = 125) + 
    annotate(geom = "text", x = as.Date("2021-01-01"), y = 125, 
             label = "@Maxwell_110", size = 3, 
             family = font.base, color = col.tw, alpha = 0.5)

for (event.num in 1:length(event.l$name)) {
    # cat(event.num, event.l$name[event.num], event.l$date[event.num])
    event.date.next.m <- as_date(paste0(
            year(event.l$date[event.num]), "-", 
            month(event.l$date[event.num]) + 1, "-01"
    ))
    p <- p + annotate(
        geom = "text", x = event.date.next.m, y = 5, 
        label = event.l$name[event.num], 
        color = event.l$color[event.num], 
        size = 2.5, family = font.base, alpha = 0.9
    )
}

plot(p)
ggsave(filename = "fig/crude-oil_01_timeline.png", 
       dpi = 300, width = 8, height = 4.8)
```

