---
title: "ggsurvfit 01"
subtitle: "Vignette"
author: "Maxwell"
date: '`r Sys.Date()`'
# bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)

# Survival Analysis
library(MASS)
library(survival)
library(survminer)
library(ggsurvfit)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "ggsurvfit-01_"
# icon.grob <- png_to_grob()

set.seed(2022)
```


# Dataset {.tabset .tabset-fade .tabset-pills}

- pair: label for pair  
- time: remission time in weeks  
- cens: censoring, 0/1  
- treat: treatment, control or 6-MP

```{r}
data("gehan")
head(gehan)
```


# Create Survival Object
```{r}
surv.obj <- Surv(time = gehan$time, event = gehan$cens)
```


# survminer
```{r}
ge.sf <- survfit(surv.obj ~ treat, data = gehan)
p1 <- ggsurvplot(
    fit = ge.sf,
    data = gehan,
    conf.int = T,
    pval = T,
    risk.table = T,
    cumevents = T,
    cumcensor = T,
    ggtheme = theme_minimal(base_family = font.base), 
    tables.theme = theme_minimal(base_family = font.base), 
    tables.height = 0.15
)
class(p1)
p1
```


# ggsurvfit
```{r}
p2 <- ggsurvfit::survfit2(surv.obj ~ treat, data = gehan) %>% 
    ggsurvfit::ggsurvfit(
        type = "survival", 
        linetype_aes = FALSE, 
        theme = theme_minimal(base_family = font.base)
    ) + 
    add_confidence_interval() + 
    add_censor_mark(shape = 4, size = 2, alpha = 0.5) + 
    add_pvalue(location  = "annotation", x = 27.5, y = 0.1, 
               color = col.os, family = font.base) + 
    # add_risktable(
    #     risktable_stats = c(
    #         "n.risk", 
    #         # "cum.event", 
    #         # "cum.censor", 
    #         "n.event", 
    #         "n.censor"
    #     ), 
    #     theme = theme_risktable_default(axis.text.y.size = 8), 
    #     size = 3, family = font.base
    # ) + 
    labs(title = "Kaplan Meier Survival Curve", 
         subtitle = "ggsurvfit package with gehen dataset", 
         caption = "@Maxwell_110", 
         x = NULL) + 
    scale_color_manual(values = c(col.plos.pink, col.plos.yellow)) + 
    scale_fill_manual(values = c(col.plos.pink, col.plos.yellow)) + 
    scale_x_continuous(breaks = scales::extended_breaks(n = 10)) + 
    theme(
        title = element_text(face = font.face, color = col.os, size = 9),
        plot.subtitle = element_text(
            face = font.face, color = col.os, size = 7
        ), 
        text = element_text(face = font.face, color = col.os, size = 10),
        plot.caption = element_text(color = "gray77", size = 5),
        axis.title = element_text(face = font.face, color = col.os),
        axis.text = element_text(face = font.face, color = col.os),
        panel.grid.major = element_line(size = 0.25),
        panel.grid.minor = element_blank(), 
        legend.position = c(0.8, 0.9), 
        legend.text = element_text(size = 6), 
        legend.key.size = unit(0.04, "npc")
    )
p2
ggsave(paste0("fig/", fn.prefix, "01.jpg"), 
       width = 6, height = 4, dpi = 300)
```


# References
- github: https://github.com/ddsjoberg/ggsurvfit  
- Vignette 1: http://www.danieldsjoberg.com/ggsurvfit/articles/gallery.html  
- Vignette 2: https://cran.r-project.org/web/packages/ggsurvfit/vignettes/themes.html  
