---
title: "CAS_nlme"
author: "HoxoMaxwell"
date: '`r Sys.Date()`'
output: 
   html_document:
      number_sections: true
      toc: true
      theme: cosmo
      highlight: tango
      code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Libraries
```{r, echo=TRUE}
library(tidyverse)
library(CASdatasets)
library(DT)
library(gridExtra)
```

# Load data
```{r}
data("usmassBI2")
datatable(
  usmassBI2,
  options = list(pageLength = 10, 
                 autoWidth = TRUE,
                 scrollX = TRUE,
                 columnDefs = list(list(width = '175px',
                                        targets = seq(1, dim(usmassBI2)[2])))),
  class = 'cell-border stripe'
  )
```

# Split data into train and validation
```{r}
train <- usmassBI2 %>% filter(YEAR < 1998)
valid <- usmassBI2 %>% filter(YEAR == 1998)
```

# EDA

## YEAR vs Average Claim
```{r, fig.width=10}
train %>% select(YEAR, AC, TOWNCODE) %>% 
  ggplot() +
  geom_line(mapping = aes(x = YEAR, y = AC, color = TOWNCODE)) +
  geom_point(mapping = aes(x = YEAR, y = AC, color = TOWNCODE)) +
  xlab('YEAR') + ylab('Average Claim')
```

## explanatory var vs Average Claim
```{r, fig.width=10}
train$lnPCI <- log(train$PCI)
train$lnPPSM <- log(train$PPSM)
p1 <- train %>% 
  select(lnPCI, AC, TOWNCODE) %>% 
  ggplot() +
  geom_line(mapping = aes(x = lnPCI, y = AC, color = TOWNCODE)) +
  geom_point(mapping = aes(x = lnPCI, y = AC, color = TOWNCODE)) +
  xlab('log-PCI') + ylab('Average Claim')
p2 <- train %>% 
  select(lnPPSM, AC, TOWNCODE) %>% 
  ggplot() +
  geom_line(mapping = aes(x = lnPPSM, y = AC, color = TOWNCODE)) +
  geom_point(mapping = aes(x = lnPPSM, y = AC, color = TOWNCODE)) +
  xlab('log-PPSM') + ylab('Average Claim')
grid.arrange(p1, p2, nrow = 1)
```

## Linear Mixed-Effects Model ( LMM )
### Error-components model
```{r}
library(nlme)
EC.fit <-
  lme(AC ~ lnPCI + lnPPSM + factor(YEAR),
  data = train,
  random = ~ 1 | TOWNCODE)
summary(EC.fit)
```


# EOF
