---
title: "googletraffic"
subtitle: "Quickstart"
author: "@Maxwell_110"
date: '`r Sys.Date()`'
# bibliography: references.bib
# link-citations: true
# zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)  # RColorBrewer::display.brewer.all()
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

# GeoSpatial Analysis
source(file = "utility/geospatial.R")
lapply(c("raster", "googletraffic"), library, character.only = T)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "googl_traffic"

font.base <- "Georgia"
ggplot2::theme_set(theme_minimal(base_family = font.base))
```


# Make raster
```{r Dataset}
r <- gt_make_raster(
    location   = c(35.695, 139.700),
    height     = 2000,
    width      = 2000,
    zoom       = 16,
    google_key = readRDS(file = "api/google-api.RDS")
)
```

# Plot
```{r}
r_df <- rasterToPoints(r, spatial = TRUE) %>% as.data.frame()
names(r_df) <- c("value", "x", "y")

ggplot() + 
    geom_raster(data = r_df,
                aes(x = x, y = y, fill = as.factor(value))) + 
    labs(fill = "Traffic\nLevel") + 
    scale_fill_manual(values = c(col.p.b, col.plos.yellow,
                                 col.pr.orange, col.rm)) + 
    coord_quickmap() +
    theme_minimal() + 
    labs(title = "Traffic Level around Shinjuku District at noon in Jan.2023", 
         subtitle = "Using <googletraffic> package developed by WorldBank", 
         caption = "@Maxwell_110") + 
    theme(
        title = element_text(
            family = font.base,
            face = "bold",
            color = col.tw,
            size = 12
        ), 
        plot.subtitle = element_text(size = 9), 
        text = element_text(family = font.base, color = col.tw),
        axis.title = element_blank(),
        axis.text = element_text(color = col.tw), 
        legend.title = element_text(size = 8), 
        plot.caption = element_text(
            family = "Times New Roman", 
            color = col.tw, size = 6, hjust = 1.1, vjust = -0.1
        ), 
        panel.grid.major = element_line(size = 0.2, color = col.fg),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = col.bg, color = col.bg)
    )

ggsave(filename = paste0("fig/", fn.prefix, ".jpg"), 
       width = 7, height = 7, dpi = 300)
```


# References
