---
title: "Plot model coefficients with ggcoef_model()"
subtitle: ""
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)  # RColorBrewer::display.brewer.all()
library(ggalt)  # geom_encircle
library(ggimage)  # geom_subview
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # fonttable(); "Candara"

library(ggstats)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "ggcoef-model_"
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
data(tips, package = "reshape")
```

# Quick coefficients plot
```{r}
mod_simple <- lm(
    formula = body_mass_g ~ ., 
    data = penguins
)
```

```{r}
p <- ggcoef_model(mod_simple) + 
    labs(title = "Forest Plot using ggstat package", 
         x = NULL, 
         subtitle = "Penguins Dataset: lm(body_mass_g ~ .)") + 
    theme(
        title = element_text(
            family = font.base, face = "bold.italic", color = col.os, size = 9
        ), 
        plot.subtitle = element_text(
            face = font.face, color = col.os, size = 7
        ), 
        text = element_text(face = font.face, color = col.os, size = 10), 
        plot.caption = element_text(color = "gray77", size = 5), 
        axis.title = element_text(
            family = font.base, face = font.face, color = col.os
        ), 
        axis.text = element_text(
            family = font.base, face = font.face, color = col.os
        ), 
        panel.grid.major = element_line(size = 0.25),
        panel.grid.minor = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.key.size = unit(0.04, "npc"), 
        # strip.text = element_text(
        #     family = font.base, face = font.face, color = col.os
        # ), 
        strip.text.y.left = ggplot2::element_text(
            family = font.base, face = font.face, color = col.os, 
            angle = 0, hjust = 0, vjust = 1
        )
    )
p
ggsave(filename = paste0("fig/", fn.prefix, "1.jpg"), 
       width = 5, height = 5)
```

# References
