---
title: "dtrack 01"
subtitle: "vignettes"
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

library(dtrackr)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
```

```{r}
ggmice::plot_pattern(data = penguins, vrb = "all", square = TRUE, 
                     rotate = FALSE, cluster = NULL) + 
    theme_minimal(base_family = font.base)
```


# Example 1
```{r}
# a pipeline parameter
cutOff <- 3

# the pipeline
dataset <- iris %>% 
    track() %>%
    status() %>%
    group_by(Species) %>% 
    status(
        short = p_count_if(Sepal.Width < cutOff),
        long = p_count_if(Sepal.Width >= cutOff),
        .messages = c(
            "consisting of {short} short sepal <{cutOff}",
            "and {long} long sepal >={cutOff}"
        )
    ) %>% 
    exclude_all(
        Petal.Width < 0.3 ~ "excluding {.excluded} with narrow petals",
        Petal.Width == max(Petal.Width) ~ "and {.excluded} outlier"
    ) %>% 
    comment("test message") %>% 
    status(.messages = "{.count} of type {Species}") %>% 
    ungroup() %>% 
    status(.messages = "{.count} together with cutOff {cutOff}")
dataset %>% flowchart("fig/dtrackr_iris.png", fontsize = 5)
```


# Example 2
```{r}
cutoff.bm <- 4000

dataset <- penguins %>% 
    track(.messages = "{.count} penguins") %>% 
    group_by(species) %>% 
    status(
        light = p_count_if(body_mass_g < cutoff.bm), 
        heavy = p_count_if(body_mass_g >= cutoff.bm), 
        .messages = c(
            "Consisting of {light} light penguins <{cutoff.bm}",
            "and {heavy} heavy penguins >={cutoff.bm}"
        )
    ) %>% 
    exclude_all(is.na(sex) ~ "Excluding {.excluded} with NA sex") %>% 
    status(.messages = "{.count} of type {species}") %>% 
    status(
        bill.length.summary = sprintf(
            "%1.2f \u00B1 %1.2f", mean(bill_length_mm), sd(bill_length_mm)
        ), 
        bill.depth.summary = sprintf(
            "%1.2f \u00B1 %1.2f", mean(bill_depth_mm), sd(bill_depth_mm)
        ), 
        .messages = c("Bill length (mm): {bill.length.summary}", 
                      "Bill depth (mm): {bill.depth.summary}")
    ) %>% 
    ungroup(.messages = "{.count} penguins")

dataset %>% flowchart("fig/dtrackr.png")
```


# References


