---
title: "ggsci"
subtitle: "Vignettes"
author: "Maxwell"
date: '`r Sys.Date()`'
bibliography: references.bib
link-citations: true
zotero: "My Library"
# abstract: \singlespacing Abstract which has to be long enough to 
#   take multiple lines otherwise one does not see the effect of single-spacing.
output: 
    html_document:
        number_sections: TRUE
        fig_caption: TRUE
        toc: TRUE
        toc_depth: 5
        toc_float: TRUE
        theme:
            bootswatch: minty
            # bootswatch: cosmo
        highlight: espresso  # espresso, tango, zenburn
        code_folding: show
        # code_download: TRUE
        fig_width: 15
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# knitr::opts_knit$set(root.dir = ".")  # modify with the location of code
```

***

# Preparations {.tabset .tabset-fade .tabset-pills}
## Packages
```{r Packages, echo=FALSE, message=FALSE}
# Data manipulation
library(tidyverse)
library(data.table)
library(janitor)  # janitor::row_to_names()
library(DT)
library(stringr)
library(lubridate)

# Visualisation
library(ggplot2)
library(ggalt)  # geom_encircle
library(patchwork)
library(broman)  # plot_crayons()
library(ggsci)  # Journal palette
library(rcartocolor)  # display_carto_all(); https://bit.ly/3Itq5kB
library(extrafont)  # "Candara"

# Interactivity
library(plotly)
library(crosstalk)

# Descriptive Statistics
library(mice)
library(ggmice)  # see src/imputation/ggmice_XX.Rmd
library(psych)
library(gtsummary)
```

## Environment
```{r Environment, echo=FALSE, message=FALSE}
source(file = "utility/environments.R")
source(file = "utility/helper_functions.R")

fn.prefix <- "_"
# icon.grob <- png_to_grob()
```


# Dataset {.tabset .tabset-fade .tabset-pills}
```{r Dataset}
data("penguins", package = "modeldata")  # modeldata from tidymodels
```

```{r}
glimpse(penguins)
tbl_summary(penguins)
```

```{r}
ggmice::plot_pattern(data = penguins, vrb = "all", square = TRUE, 
                     rotate = TRUE, cluster = NULL) + 
    theme_minimal(base_family = font.base) + 
    theme(text = element_text(face = font.face), 
          axis.text.x.top = element_text(angle = 90))
```


```{r}
penguins <- penguins %>% filter(!is.na(body_mass_g))
```


# ggsci
```{r}
p.base <- penguins %>% 
    ggplot(aes(x = body_mass_g, y = bill_length_mm, color = species)) + 
    geom_point(alpha = 0.6, size = 0.75) + 
    geom_smooth(alpha = 0.2, size = 0.4)
```

## npg
```{r}
p.npg <- p.base + 
    scale_color_npg() + 
    labs(title = "Nature Publishing Group", 
         subtitle = "An Example using penguin dataset") + 
    theme(
        title = element_text(size = 9), 
        legend.position = c(0.8, 0.2)
    )
```

## Lancet
```{r}
p.lancet <- p.base + 
    scale_color_lancet() + 
    labs(title = "Lancet") + 
    theme(
        title = element_text(size = 9), 
        legend.position = "none", 
        axis.title = element_blank()
    )
```

## NEJM
```{r}
p.nejm <- p.base + 
    scale_color_nejm() + 
    labs(title = "NEJM", 
         caption = "@Maxwell_110") + 
    theme(
        title = element_text(size = 9), 
        legend.position = "none", 
        axis.title = element_blank()
    )
```

```{r}
p.npg + p.lancet + p.nejm
ggsave("fig/ggsci.jpg", width = 3.5 * 3, height = 3.5)
```


# References


